#!/usr/bin/env bash
# tests/generate.sh — regression check for bin/pln-generate.
#
# The generator is the one piece of real logic the host seam adds, and the
# property the whole design rests on is an *absence*: the copy of a skill a
# model reads must contain its own host's mechanics and nothing addressed to the
# other host. So every case here asserts both directions — what is present and
# what must not be.
#
# Two halves:
#
#   1. Fixtures. A throwaway repo with its own src/ tree exercises the three
#      directives, the generated-by banner, nested targets, --list, --clean, and
#      every error path, without depending on the real skill text.
#   2. The real sources. Both hosts are generated into temp dirs and grepped for
#      the other host's mechanics, for leftover directives, and for the
#      placeholder text that means nothing was built.
#
# Needs no network, no Codex install, and never writes to the working tree.
#
# Run:  bash tests/generate.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BIN="$REPO_DIR/bin/pln-generate"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/pln-generate-test.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

fail() { echo "FAIL: $*" >&2; exit 1; }

has() { grep -qF -- "$2" "$1" || fail "$3"; }
hasnt() { grep -qF -- "$2" "$1" && fail "$3"; return 0; }

# ─── a throwaway repo the generator can be pointed at ─────────────────────────
# bin/pln-generate resolves its sources relative to its own location, so a copy
# in a fixture tree reads that tree's src/ and nothing of the real one.
new_repo() { # new_repo <dir>
  local d="$1"
  mkdir -p "$d/bin" "$d/src/hosts/claude" "$d/src/hosts/codex"
  cp "$BIN" "$d/bin/pln-generate"
  printf 'TOOL=Workflow\nAMPER=stays & literal\n' > "$d/src/hosts/claude/vars"
  printf 'TOOL=codex exec\nAMPER=stays & literal\n' > "$d/src/hosts/codex/vars"
}

R="$WORK/fixture"
new_repo "$R"

printf 'Claude greeting fragment.\nIt calls {{TOOL}}.\n' > "$R/src/hosts/claude/greeting.md"
printf 'Codex greeting fragment.\nIt calls {{TOOL}}.\n' > "$R/src/hosts/codex/greeting.md"

cat > "$R/src/SKILL.core.md" <<'CORE'
---
name: fixture
---

# Fixture skill

<!-- pln:include greeting -->

<!-- pln:only claude -->
Claude-only body: spawn the item agent with the Workflow tool.
<!-- pln:endonly -->
<!-- pln:only codex -->
Codex-only body: spawn the item agent with bin/pln-codex-agent.
<!-- pln:endonly -->

Shared tail, and an ampersand that {{AMPER}}.
CORE

mkdir -p "$R/src/nested"
cat > "$R/src/nested/OTHER.core.md" <<'CORE'
---
name: fixture-nested
---
Nested target for {{TOOL}}.
CORE

# ─── --list names every target, relative and sorted ───────────────────────────
list="$("$R/bin/pln-generate" --list)"
[ "$list" = "$(printf 'SKILL.md\nnested/OTHER.md')" ] \
  || fail "--list printed: $list"

# ─── a claude build: own mechanics in, the other host's out ───────────────────
out_c="$WORK/out-claude"
"$R/bin/pln-generate" --host claude --out-dir "$out_c" >/dev/null
f="$out_c/SKILL.md"
has "$f" 'Claude greeting fragment.' "claude build lost its fragment"
has "$f" 'It calls Workflow.' "{{TOOL}} was not substituted inside a fragment"
has "$f" 'Claude-only body' "claude build lost its pln:only block"
has "$f" 'Shared tail' "claude build lost the shared body"
has "$f" 'an ampersand that stays & literal' "a & in a vars value was mangled"
hasnt "$f" 'Codex greeting fragment.' "the codex fragment leaked into the claude build"
hasnt "$f" 'Codex-only body' "the codex pln:only block leaked into the claude build"
hasnt "$f" 'pln-codex-agent' "codex mechanics leaked into the claude build"

# ─── a codex build: the mirror image ──────────────────────────────────────────
out_x="$WORK/out-codex"
"$R/bin/pln-generate" --host codex --out-dir "$out_x" >/dev/null
f="$out_x/SKILL.md"
has "$f" 'Codex greeting fragment.' "codex build lost its fragment"
has "$f" 'It calls codex exec.' "{{TOOL}} was not substituted for codex"
has "$f" 'Codex-only body' "codex build lost its pln:only block"
has "$f" 'Shared tail' "codex build lost the shared body"
hasnt "$f" 'Claude greeting fragment.' "the claude fragment leaked into the codex build"
hasnt "$f" 'Claude-only body' "the claude pln:only block leaked into the codex build"
hasnt "$f" 'Workflow' "claude mechanics leaked into the codex build"

# ─── nested targets land at the same relative path ────────────────────────────
[ -f "$out_x/nested/OTHER.md" ] || fail "a nested target was not written under out-dir"
has "$out_x/nested/OTHER.md" 'Nested target for codex exec.' "nested target not rendered"

# ─── the banner is stamped, and after the frontmatter ─────────────────────────
for f in "$out_c/SKILL.md" "$out_x/SKILL.md"; do
  [ "$(sed -n 1p "$f")" = "---" ] || fail "$f does not start with YAML frontmatter"
  [ "$(sed -n 3p "$f")" = "---" ] || fail "$f banner displaced the frontmatter"
  has "$f" 'Generated by bin/pln-generate' "$f carries no generated-by banner"
  has "$f" 'Edit src/ and run ./setup' "$f banner does not say where to edit"
done
grep -qF 'for the claude host' "$out_c/SKILL.md" || fail "banner names the wrong host"
grep -qF 'for the codex host' "$out_x/SKILL.md" || fail "banner names the wrong host"

# ─── no directive survives into the output ────────────────────────────────────
for f in "$out_c/SKILL.md" "$out_x/SKILL.md" "$out_x/nested/OTHER.md"; do
  for d in 'pln:include' 'pln:only' 'pln:endonly' '{{'; do
    hasnt "$f" "$d" "unconsumed '$d' left in $f"
  done
done

# ─── error paths: non-zero exit, and the target left untouched ────────────────
# Each case gets its own single-target repo so the failure is unambiguous.
bad_repo() { # bad_repo <name> <core-body...>  → prints the repo dir
  local d="$WORK/bad-$1"
  new_repo "$d"
  printf 'Codex greeting fragment.\n' > "$d/src/hosts/codex/greeting.md"
  printf 'Claude greeting fragment.\n' > "$d/src/hosts/claude/greeting.md"
  cat > "$d/src/SKILL.core.md"
  printf '%s' "$d"
}

expect_fail() { # expect_fail <repo> <description> <args...>
  local d="$1" what="$2"; shift 2
  local target="$d/SKILL.md" rc=0
  printf 'sentinel\n' > "$target"
  "$d/bin/pln-generate" "$@" >/dev/null 2>&1 || rc=$?
  [ "$rc" -ne 0 ] || fail "$what exited 0 (expected non-zero)"
  [ "$(cat "$target")" = "sentinel" ] || fail "$what overwrote the target file"
}

d="$(bad_repo missing-fragment <<'CORE'
---
name: x
---
<!-- pln:include nowhere -->
CORE
)"
expect_fail "$d" "an include of a fragment that does not exist" --host codex --out-dir "$d"

d="$(bad_repo unclosed <<'CORE'
---
name: x
---
<!-- pln:only codex -->
body
CORE
)"
expect_fail "$d" "an unclosed pln:only block" --host codex --out-dir "$d"

d="$(bad_repo stray-end <<'CORE'
---
name: x
---
<!-- pln:endonly -->
CORE
)"
expect_fail "$d" "a pln:endonly with no pln:only" --host codex --out-dir "$d"

d="$(bad_repo nested-only <<'CORE'
---
name: x
---
<!-- pln:only codex -->
<!-- pln:only claude -->
<!-- pln:endonly -->
<!-- pln:endonly -->
CORE
)"
expect_fail "$d" "a nested pln:only block" --host codex --out-dir "$d"

d="$(bad_repo malformed <<'CORE'
---
name: x
---
<!-- pln:include two words -->
CORE
)"
expect_fail "$d" "a pln:include with a malformed argument" --host codex --out-dir "$d"

d="$(bad_repo no-frontmatter <<'CORE'
# A core file with no YAML frontmatter
CORE
)"
expect_fail "$d" "a core file with nowhere to stamp the banner" --host codex --out-dir "$d"

# An unknown host, and no host at all, are both refused before anything is read.
d="$(bad_repo no-host <<'CORE'
---
name: x
---
body
CORE
)"
expect_fail "$d" "an unknown host" --host solaris --out-dir "$d"
expect_fail "$d" "no host at all" --out-dir "$d"
rm -rf "$d/src/hosts/codex"
expect_fail "$d" "a host with no fragment directory" --host codex --out-dir "$d"

# ─── --clean puts the tracked placeholders back ───────────────────────────────
# This is what keeps an upgrade's `git stash` from seeing a permanently-modified
# tracked file, so it is worth a real git checkout rather than a mock.
G="$WORK/gitrepo"
new_repo "$G"
printf 'Claude greeting fragment.\n' > "$G/src/hosts/claude/greeting.md"
cat > "$G/src/SKILL.core.md" <<'CORE'
---
name: x
---
<!-- pln:include greeting -->
CORE
printf -- '---\nname: x\n---\nplaceholder, run ./setup\n' > "$G/SKILL.md"
git -C "$G" init -q
git -C "$G" add -A
git -C "$G" -c user.name=t -c user.email=t@example.com commit -qm init
"$G/bin/pln-generate" claude >/dev/null
grep -qF 'placeholder, run ./setup' "$G/SKILL.md" && fail "generate did not overwrite the placeholder"
[ -n "$(git -C "$G" status --porcelain SKILL.md)" ] || fail "generate left SKILL.md unmodified in git"
"$G/bin/pln-generate" --clean
grep -qF 'placeholder, run ./setup' "$G/SKILL.md" || fail "--clean did not restore the placeholder"
[ -z "$(git -C "$G" status --porcelain SKILL.md)" ] || fail "--clean left a dirty tree"

# Outside a git checkout --clean has nothing to restore, and says so rather than
# failing the install that called it.
N="$WORK/nogit"
new_repo "$N"
cat > "$N/src/SKILL.core.md" <<'CORE'
---
name: x
---
body
CORE
"$N/bin/pln-generate" --clean 2>/dev/null || fail "--clean outside a git checkout exited non-zero"

# ─── the real sources, both hosts ─────────────────────────────────────────────
# The fixtures above prove the mechanism; these prove the shipped text actually
# splits. Generated into temp dirs — the working tree is never written to.
real_c="$WORK/real-claude"
real_x="$WORK/real-codex"
"$BIN" --host claude --out-dir "$real_c" >/dev/null
"$BIN" --host codex --out-dir "$real_x" >/dev/null

targets="$("$BIN" --list)"
[ -n "$targets" ] || fail "the real sources declare no targets"

while IFS= read -r t; do
  for f in "$real_c/$t" "$real_x/$t"; do
    [ -f "$f" ] || fail "$t was not generated"
    has "$f" 'Generated by bin/pln-generate' "$f carries no generated-by banner"
    hasnt "$f" 'not built yet' "$f still holds the placeholder text"
    for d in 'pln:include' 'pln:only' 'pln:endonly' '{{'; do
      hasnt "$f" "$d" "unconsumed '$d' left in $f"
    done
  done

  # Claude mechanics that must never reach a Codex build.
  for term in Workflow PushNotification ToolSearch resumeFromRunId agentType \
    CLAUDE_SKILL_DIR 'Skill tool'; do
    hasnt "$real_x/$t" "$term" "'$term' leaked into the codex build of $t"
  done

  # Codex mechanics that must never reach a Claude build. `codex exec` itself is
  # not on this list: pln-pr's opt-in cross-model review pass calls it on Claude
  # too, deliberately and read-only.
  for term in pln-codex-agent CODEX_HOME 'codex exec resume' workspace-write; do
    hasnt "$real_c/$t" "$term" "'$term' leaked into the claude build of $t"
  done
done <<< "$targets"

# Each build must actually carry its own host's spawn mechanism, or the absence
# checks above would pass on an empty file.
has "$real_c/SKILL.md" 'Workflow' "the claude build has no Workflow mechanics"
has "$real_x/SKILL.md" 'pln-codex-agent' "the codex build has no Codex agent mechanics"

# ─── and nothing above touched the working tree ───────────────────────────────
if [ -d "$REPO_DIR/.git" ]; then
  dirty="$(git -C "$REPO_DIR" status --porcelain -- $targets)"
  [ -z "$dirty" ] || fail "the test modified tracked skill files: $dirty"
fi

echo "OK"
